### PR TITLE
chore: Update version to 100.x.x

### PR DESCRIPTION
**Pull request by phated**
This is a draft proposal to update all of the dependencies to version `100.x.x`. The reason I'm proposing that is that DF has already claimed the major version number to match their minor, such as `6.x.x` for 0.6; and @dfdao has published some renamed packages with that versioning already. Since the npm registry is immutable, we have to choose some version scheme that isn't likely to get used, and in that I chose "100".

Let me know what you think.

### CODE REVIEW

**Comment by cha0sg0d** [comment]
Sure why not 💯

**Comment by cha0sg0d** [comment]
Or `10` ?

**Review by cha0sg0d — APPROVED** [review]
woohoo

**Comment by phated** [comment]
Sounds like we are choosing 100 because we could see a world where DF releases v10 but not necessarily v100

**Pull request merged**
