### PR TITLE
chore: Remove lerna from project & cleanup unused scripts

### PR DESCRIPTION
**Pull request by phated**
This removes lerna from the project and converts the one usage to `npm run --workspaces`. It also changes all `--workspaces` commands to use `--if-present` (as documented at https://docs.npmjs.com/cli/v8/using-npm/workspaces#ignoring-missing-scripts).

The primary reasons lerna was used in DF:
1. You couldn't scope your workspace commands, so the `docs` command would fail in the circuits and eth workspaces
2. Yarn didn't have a workspaces publish command

Since npm allows us to use `--if-present` and it allows publish with `--workspaces`, we no longer need lerna in the project at all.

We can also remove all of the `exit 0` stub scripts because we can just use the `--if-present` flag 🎉 

I had to sneak a gl-matrix fix into this PR because it seems [3.4.3 doesn't contain typescript types](https://github.com/toji/gl-matrix/issues/440)

### CODE REVIEW

**Comment by phated** [comment]
Note: I haven't tried the `npm publish --workspaces` command with private packages. I only use it in https://github.com/projectsophon/zkgame-primitives which supplies **only** public packages.

**Review by cha0sg0d — APPROVED** [review]
nice and clean and satisfying

**Comment by cha0sg0d** [comment]
> Note: I haven't tried the `npm publish --workspaces` command with private packages. I only use it in https://github.com/projectsophon/zkgame-primitives which supplies **only** public packages.

I don't think that will be a problem for us. Also looks like the `npm publish --workspaces` works just fine with private packages, just requires a paid account. 

https://docs.npmjs.com/cli/v8/using-npm/workspaces#ignoring-missing-scripts

**Comment by phated** [comment]
To be clear, not "private packages" but the `"private": true` flag in the package.json files which means "don't publish this"

**Comment by cha0sg0d** [comment]
Ah I see. What is a use case where you have open source packages but don't publish them?

**Comment by phated** [comment]
> Ah I see. What is a use case where you have open source packages but don't publish them?

You don't publish "applications" like `circuits`, `client` and `eth` workspaces. Those are all marked as `private` to ensure they don't get published to the npm registry.

**Comment by cha0sg0d** [comment]
Got it. What's the easiest way to test this? run `npm publish --workspaces` to the dfdao account and see what happens? Or put a dummy private package in `zkgame-primitives` and test?

**Comment by phated** [comment]
> What's the easiest way to test this?

I think we'll just test it when we go to publish some dfdao packages and see what happens.

**Pull request merged**
